export const states = [
  { id: 1,  value: 'AC', label: 'Acre' },
  { id: 2,  value: 'AL', label: 'Alagoas' },
  { id: 3,  value: 'AM', label: 'Amazonas' },
  { id: 4,  value: 'AP', label: 'Amapá' },
  { id: 5,  value: 'BA', label: 'Bahia' },
  { id: 6,  value: 'CE', label: 'Ceará' },
  { id: 7,  value: 'DF', label: 'Distrito Federal' },
  { id: 8,  value: 'ES', label: 'Espírito Santo' },
  { id: 9,  value: 'GO', label: 'Goiás' },
  { id: 10, value: 'MA', label: 'Maranhão' },
  { id: 11, value: 'MG', label: 'Minas Gerais' },
  { id: 12, value: 'MS', label: 'Mato Grosso do Sul' },
  { id: 13, value: 'MT', label: 'Mato Grosso' },
  { id: 14, value: 'PA', label: 'Pará' },
  { id: 15, value: 'PB', label: 'Paraíba' },
  { id: 16, value: 'PE', label: 'Pernambuco' },
  { id: 17, value: 'PI', label: 'Piauí' },
  { id: 18, value: 'PR', label: 'Paraná' },
  { id: 19, value: 'RJ', label: 'Rio de Janeiro' },
  { id: 20, value: 'RN', label: 'Rio Grande do Norte' },
  { id: 21, value: 'RO', label: 'Rondônia' },
  { id: 22, value: 'RR', label: 'Roraima' },
  { id: 23, value: 'RS', label: 'Rio Grande do Sul' },
  { id: 24, value: 'SC', label: 'Santa Catarina' },
  { id: 25, value: 'SE', label: 'Sergipe' },
  { id: 26, value: 'SP', label: 'São Paulo' },
  { id: 27, value: 'TO', label: 'Tocantins' }
];

export const parties = [
  { id: 36898, value: 'AVANTE',  label: 'Avante' },
  { id: 36769, value: 'DEM',     label: 'Democratas' },
  { id: 36899, value: 'MDB',     label: 'Movimento Democrático Brasileiro' },
  { id: 37900, value: 'PATRI',   label: 'Patriota' },
  { id: 36779, value: 'PCdoB',   label: 'Partido Comunista do Brasil' },
  { id: 36786, value: 'PDT',     label: 'Partido Democrático Trabalhista' },
  { id: 36761, value: 'PEN',     label: 'Partido Ecológico Nacional' },
  { id: 36793, value: 'PHS',     label: 'Partido Humanista da Solidariedade' },
  { id: 36887, value: 'PMB',     label: 'Partido da Mulher Brasileira' },
  { id: 36800, value: 'PMDB',    label: 'Partido do Movimento Democrático Brasileiro' },
  { id: 36801, value: 'PMN',     label: 'Partido da Mobilização Nacional' },
  { id: 36896, value: 'PODE',    label: 'Podemos' },
  { id: 36809, value: 'PP',      label: 'Partido Progressista' },
  { id: 36762, value: 'PPL',     label: 'Partido Pátria Livre' },
  { id: 36813, value: 'PPS',     label: 'Partido Popular Socialista' },
  { id: 36814, value: 'PR',      label: 'Partido da República' },
  { id: 36815, value: 'PRB',     label: 'Partido Republicano Brasileiro' },
  { id: 36763, value: 'PROS',    label: 'Partido Republicano da Ordem Social' },
  { id: 36824, value: 'PRP',     label: 'Partido Republicano Progressista' },
  { id: 36829, value: 'PRTB',    label: 'Partido Renovador Trabalhista Brasileiro' },
  { id: 36832, value: 'PSB',     label: 'Partido Socialista Brasileiro' },
  { id: 36833, value: 'PSC',     label: 'Partido Social Cristão' },
  { id: 36834, value: 'PSD',     label: 'Partido Social Democrático' },
  { id: 36835, value: 'PSDB',    label: 'Partido da Social Democracia Brasileira' },
  { id: 36836, value: 'PSDC',    label: 'Partido Social Democrata Cristão' },
  { id: 36837, value: 'PSL',     label: 'Partido Social Liberal' },
  { id: 36839, value: 'PSOL',    label: 'Partido Socialismo e Liberdade' },
  { id: 36844, value: 'PT',      label: 'Partido dos Trabalhadores' },
  { id: 36845, value: 'PTB',     label: 'Partido Trabalhista Brasileiro' },
  { id: 36846, value: 'PTC',     label: 'Partido Trabalhista Cristão' },
  { id: 36847, value: 'PTdoB',   label: 'Partido Trabalhista do Brasil' },
  { id: 36848, value: 'PTN',     label: 'Partido Trabalhista Nacional' },
  { id: 36851, value: 'PV',      label: 'Partido Verde' },
  { id: 36886, value: 'REDE',    label: 'Rede Sustentabilidade' },
  { id: 36852, value: 'S.PART.', label: 'Sem Partido' },
  { id: 36765, value: 'SD',      label: 'Solidariedade' }
];
